name: Production Deploy
on:
  push:
    branches: [master]


jobs:
  deploy:
    name: FTP deploy action
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.2.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: ${{ secrets.FTP_SERVER_DIR }}
